// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6yOh7XaZA7UU43fdKh9hSsl3usUvD1Ug',
    appId: '1:747052199218:web:20c11c8adbbc020fecfb2b',
    messagingSenderId: '747052199218',
    projectId: 'ballot-cb8e0',
    authDomain: 'ballot-cb8e0.firebaseapp.com',
    storageBucket: 'ballot-cb8e0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9Rh2KSon8LFOEaTbzBenUXWooo2ijKvU',
    appId: '1:747052199218:android:50f3e10a5d1e32e4ecfb2b',
    messagingSenderId: '747052199218',
    projectId: 'ballot-cb8e0',
    storageBucket: 'ballot-cb8e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnwcOUKfxfyfsSQe9iLXiffhv-i6biHKg',
    appId: '1:747052199218:ios:a0dbbdce1ce2fd08ecfb2b',
    messagingSenderId: '747052199218',
    projectId: 'ballot-cb8e0',
    storageBucket: 'ballot-cb8e0.appspot.com',
    iosClientId: '747052199218-l1dneshbej5b4m9pln5roko03r6sscfd.apps.googleusercontent.com',
    iosBundleId: 'com.example.ballotBox',
  );
}
